
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Warkarma (https://sketchfab.com/warkarma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2018-flat-screen-tv-d885976821324ceb8fa4f1fa569b0295
Title: 2018 Flat screen TV
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

const DemoComputer = (props) => {
  const { nodes, materials } = useGLTF('./models/screen.glb')
  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4');
  const group = useRef();

  useEffect(() => {
    if (txt) {
      // txt.flipY = false;
      // txt.wrapS = txt.wrapT = THREE.RepeatWrapping;
    }
  }, [txt]);

  useGSAP(() => {
    gsap.from(group.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: 'power3.out',
    });
  }, [txt]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.995}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="tv2018">
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials['02___Default']}
              >
                <mesh position={[0, 0, 0]} scale={[1.9, 1, 1]}>
                  <planeGeometry args={[1, 1]} />
                  <meshBasicMaterial map={txt} toneMapped={false} />
                </mesh>
              </mesh>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/screen.glb')

export default DemoComputer;