/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: agustin.trezza (https://sketchfab.com/agustin.trezza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-1-e6a5af39d2b3495fb4fb1f8f94d3efda
Title: Javascript (1)
*/

import { Float, useGLTF } from '@react-three/drei';

export const JSLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/javascript_1.glb')
  return (
    <Float dispose={null}>
      <group {...props} scale={0.05} rotation={[0, Math.PI / 4, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.mat_3220964}
          rotation={[-Math.PI / 2, -1, 0]}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/javascript_1.glb')


export default JSLogo;